# Generated by Django 3.0.1 on 2019-12-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='close_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='spaces',
            name='open_time',
            field=models.CharField(max_length=30),
        ),
    ]
