# Generated by Django 3.0.1 on 2019-12-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_space_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='amenity_space',
            field=models.ManyToManyField(through='space.Space_Amenities', to='space.Amenities'),
        ),
    ]
